module Evergreen.Migrate.V18 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V17.ConfirmComponent
import Evergreen.V17.Filter
import Evergreen.V17.FormDict
import Evergreen.V17.Gen.Model
import Evergreen.V17.Gen.Pages
import Evergreen.V17.Gen.Params.Routes.Filter_
import Evergreen.V17.Gen.Params.SignIn.SignInDest_
import Evergreen.V17.Pages.Admin.AddUser
import Evergreen.V17.Pages.Admin.ChangePassword
import Evergreen.V17.Pages.Admin.Home_
import Evergreen.V17.Pages.Admin.RemoveUser
import Evergreen.V17.Pages.Admin.ShowJson
import Evergreen.V17.Pages.ChangePassword
import Evergreen.V17.Pages.Home_
import Evergreen.V17.Pages.InputJson
import Evergreen.V17.Pages.MoreOptions
import Evergreen.V17.Pages.NewRoute
import Evergreen.V17.Pages.OutputJson
import Evergreen.V17.Pages.Routes.Filter_
import Evergreen.V17.Pages.SignIn.SignInDest_
import Evergreen.V17.Pages.Stats
import Evergreen.V17.Route
import Evergreen.V17.RouteEditPane
import Evergreen.V17.Shared
import Evergreen.V17.Sorter
import Evergreen.V17.Types
import Evergreen.V18.ConfirmComponent
import Evergreen.V18.Filter
import Evergreen.V18.FormDict
import Evergreen.V18.Gen.Model
import Evergreen.V18.Gen.Pages
import Evergreen.V18.Gen.Params.Routes.Filter_
import Evergreen.V18.Gen.Params.SignIn.SignInDest_
import Evergreen.V18.Pages.Admin.AddUser
import Evergreen.V18.Pages.Admin.ChangePassword
import Evergreen.V18.Pages.Admin.Home_
import Evergreen.V18.Pages.Admin.RemoveUser
import Evergreen.V18.Pages.Admin.ShowJson
import Evergreen.V18.Pages.ChangePassword
import Evergreen.V18.Pages.Home_
import Evergreen.V18.Pages.InputJson
import Evergreen.V18.Pages.MoreOptions
import Evergreen.V18.Pages.NewRoute
import Evergreen.V18.Pages.OutputJson
import Evergreen.V18.Pages.Routes.Filter_
import Evergreen.V18.Pages.SignIn.SignInDest_
import Evergreen.V18.Pages.Stats
import Evergreen.V18.Route
import Evergreen.V18.RouteEditPane
import Evergreen.V18.Shared
import Evergreen.V18.Sorter
import Evergreen.V18.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V17.Types.FrontendModel -> ModelMigration Evergreen.V18.Types.FrontendModel Evergreen.V18.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V17.Types.BackendModel -> ModelMigration Evergreen.V18.Types.BackendModel Evergreen.V18.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V17.Types.FrontendMsg -> MsgMigration Evergreen.V18.Types.FrontendMsg Evergreen.V18.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V17.Types.ToBackend -> MsgMigration Evergreen.V18.Types.ToBackend Evergreen.V18.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V17.Types.BackendMsg -> MsgMigration Evergreen.V18.Types.BackendMsg Evergreen.V18.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V17.Types.ToFrontend -> MsgMigration Evergreen.V18.Types.ToFrontend Evergreen.V18.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V17.Types.FrontendModel -> Evergreen.V18.Types.FrontendModel
migrate_Types_FrontendModel old =
    { url = old.url
    , key = old.key
    , shared = old.shared |> migrate_Shared_Model
    , page = old.page |> migrate_Gen_Pages_Model
    }


migrate_ConfirmComponent_State : Evergreen.V17.ConfirmComponent.State -> Evergreen.V18.ConfirmComponent.State
migrate_ConfirmComponent_State old =
    case old of
        Evergreen.V17.ConfirmComponent.Waiting ->
            Evergreen.V18.ConfirmComponent.Waiting

        Evergreen.V17.ConfirmComponent.Active p0 ->
            Evergreen.V18.ConfirmComponent.Active p0


migrate_Filter_Model : Evergreen.V17.Filter.Model -> Evergreen.V18.Filter.Model
migrate_Filter_Model old =
    { grade = old.grade
    , type_ = old.type_
    , tickdate = old.tickdate |> migrate_Filter_TickDateFilter
    }


migrate_Filter_TickDateFilter : Evergreen.V17.Filter.TickDateFilter -> Evergreen.V18.Filter.TickDateFilter
migrate_Filter_TickDateFilter old =
    case old of
        Evergreen.V17.Filter.TickdateRangeFrom ->
            Evergreen.V18.Filter.TickdateRangeFrom

        Evergreen.V17.Filter.TickdateRangeTo ->
            Evergreen.V18.Filter.TickdateRangeTo

        Evergreen.V17.Filter.TickdateRangeBetween ->
            Evergreen.V18.Filter.TickdateRangeBetween

        Evergreen.V17.Filter.ShowHasTickdate ->
            Evergreen.V18.Filter.ShowHasTickdate

        Evergreen.V17.Filter.ShowWithoutTickdate ->
            Evergreen.V18.Filter.ShowWithoutTickdate

        Evergreen.V17.Filter.ShowAllTickdates ->
            Evergreen.V18.Filter.ShowAllTickdates


migrate_FormDict_FormDict : Evergreen.V17.FormDict.FormDict -> Evergreen.V18.FormDict.FormDict
migrate_FormDict_FormDict old =
    case old of
        Evergreen.V17.FormDict.FormDict p0 ->
            Evergreen.V18.FormDict.FormDict p0


migrate_Gen_Model_Model : Evergreen.V17.Gen.Model.Model -> Evergreen.V18.Gen.Model.Model
migrate_Gen_Model_Model old =
    case old of
        Evergreen.V17.Gen.Model.Redirecting_ ->
            Evergreen.V18.Gen.Model.Redirecting_

        Evergreen.V17.Gen.Model.ChangePassword p0 p1 ->
            Evergreen.V18.Gen.Model.ChangePassword p0 (p1 |> migrate_Pages_ChangePassword_Model)

        Evergreen.V17.Gen.Model.Home_ p0 p1 ->
            Evergreen.V18.Gen.Model.Home_ p0 (p1 |> migrate_Pages_Home__Model)

        Evergreen.V17.Gen.Model.InputJson p0 p1 ->
            Evergreen.V18.Gen.Model.InputJson p0 (p1 |> migrate_Pages_InputJson_Model)

        Evergreen.V17.Gen.Model.MoreOptions p0 p1 ->
            Evergreen.V18.Gen.Model.MoreOptions p0 (p1 |> migrate_Pages_MoreOptions_Model)

        Evergreen.V17.Gen.Model.NewRoute p0 p1 ->
            Evergreen.V18.Gen.Model.NewRoute p0 (p1 |> migrate_Pages_NewRoute_Model)

        Evergreen.V17.Gen.Model.OutputJson p0 p1 ->
            Evergreen.V18.Gen.Model.OutputJson p0 (p1 |> migrate_Pages_OutputJson_Model)

        Evergreen.V17.Gen.Model.Stats p0 p1 ->
            Evergreen.V18.Gen.Model.Stats p0 (p1 |> migrate_Pages_Stats_Model)

        Evergreen.V17.Gen.Model.Admin__AddUser p0 p1 ->
            Evergreen.V18.Gen.Model.Admin__AddUser p0 (p1 |> migrate_Pages_Admin_AddUser_Model)

        Evergreen.V17.Gen.Model.Admin__ChangePassword p0 p1 ->
            Evergreen.V18.Gen.Model.Admin__ChangePassword p0
                (p1 |> migrate_Pages_Admin_ChangePassword_Model)

        Evergreen.V17.Gen.Model.Admin__Home_ p0 p1 ->
            Evergreen.V18.Gen.Model.Admin__Home_ p0 (p1 |> migrate_Pages_Admin_Home__Model)

        Evergreen.V17.Gen.Model.Admin__RemoveUser p0 p1 ->
            Evergreen.V18.Gen.Model.Admin__RemoveUser p0 (p1 |> migrate_Pages_Admin_RemoveUser_Model)

        Evergreen.V17.Gen.Model.Admin__ShowJson p0 p1 ->
            Evergreen.V18.Gen.Model.Admin__ShowJson p0 (p1 |> migrate_Pages_Admin_ShowJson_Model)

        Evergreen.V17.Gen.Model.Routes__Filter_ p0 p1 ->
            Evergreen.V18.Gen.Model.Routes__Filter_ (p0 |> migrate_Gen_Params_Routes_Filter__Params)
                (p1 |> migrate_Pages_Routes_Filter__Model)

        Evergreen.V17.Gen.Model.SignIn__SignInDest_ p0 p1 ->
            Evergreen.V18.Gen.Model.SignIn__SignInDest_ (p0 |> migrate_Gen_Params_SignIn_SignInDest__Params)
                (p1 |> migrate_Pages_SignIn_SignInDest__Model)

        Evergreen.V17.Gen.Model.NotFound p0 ->
            Evergreen.V18.Gen.Model.NotFound p0


migrate_Gen_Pages_Model : Evergreen.V17.Gen.Pages.Model -> Evergreen.V18.Gen.Pages.Model
migrate_Gen_Pages_Model old =
    old |> migrate_Gen_Model_Model


migrate_Gen_Params_Routes_Filter__Params : Evergreen.V17.Gen.Params.Routes.Filter_.Params -> Evergreen.V18.Gen.Params.Routes.Filter_.Params
migrate_Gen_Params_Routes_Filter__Params old =
    old


migrate_Gen_Params_SignIn_SignInDest__Params : Evergreen.V17.Gen.Params.SignIn.SignInDest_.Params -> Evergreen.V18.Gen.Params.SignIn.SignInDest_.Params
migrate_Gen_Params_SignIn_SignInDest__Params old =
    old


migrate_Pages_Admin_AddUser_Model : Evergreen.V17.Pages.Admin.AddUser.Model -> Evergreen.V18.Pages.Admin.AddUser.Model
migrate_Pages_Admin_AddUser_Model old =
    { form = old.form |> migrate_FormDict_FormDict
    }


migrate_Pages_Admin_ChangePassword_Model : Evergreen.V17.Pages.Admin.ChangePassword.Model -> Evergreen.V18.Pages.Admin.ChangePassword.Model
migrate_Pages_Admin_ChangePassword_Model old =
    { form = old.form |> migrate_FormDict_FormDict
    }


migrate_Pages_Admin_Home__Model : Evergreen.V17.Pages.Admin.Home_.Model -> Evergreen.V18.Pages.Admin.Home_.Model
migrate_Pages_Admin_Home__Model old =
    old


migrate_Pages_Admin_RemoveUser_Model : Evergreen.V17.Pages.Admin.RemoveUser.Model -> Evergreen.V18.Pages.Admin.RemoveUser.Model
migrate_Pages_Admin_RemoveUser_Model old =
    old


migrate_Pages_Admin_ShowJson_Model : Evergreen.V17.Pages.Admin.ShowJson.Model -> Evergreen.V18.Pages.Admin.ShowJson.Model
migrate_Pages_Admin_ShowJson_Model old =
    old


migrate_Pages_ChangePassword_Model : Evergreen.V17.Pages.ChangePassword.Model -> Evergreen.V18.Pages.ChangePassword.Model
migrate_Pages_ChangePassword_Model old =
    old


migrate_Pages_Home__Model : Evergreen.V17.Pages.Home_.Model -> Evergreen.V18.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_InputJson_Model : Evergreen.V17.Pages.InputJson.Model -> Evergreen.V18.Pages.InputJson.Model
migrate_Pages_InputJson_Model old =
    { text = old.text
    , statusText = old.statusText
    , parsedRoutes = old.parsedRoutes |> Maybe.map (List.map migrate_Route_NewRouteData)
    , confirmState = old.confirmState |> migrate_ConfirmComponent_State
    }


migrate_Pages_MoreOptions_Model : Evergreen.V17.Pages.MoreOptions.Model -> Evergreen.V18.Pages.MoreOptions.Model
migrate_Pages_MoreOptions_Model old =
    old


migrate_Pages_NewRoute_Model : Evergreen.V17.Pages.NewRoute.Model -> Evergreen.V18.Pages.NewRoute.Model
migrate_Pages_NewRoute_Model old =
    { newRouteData = old.newRouteData |> migrate_RouteEditPane_Model
    }


migrate_Pages_OutputJson_Model : Evergreen.V17.Pages.OutputJson.Model -> Evergreen.V18.Pages.OutputJson.Model
migrate_Pages_OutputJson_Model old =
    old


migrate_Pages_Routes_Filter__Filter : Evergreen.V17.Pages.Routes.Filter_.Filter -> Evergreen.V18.Pages.Routes.Filter_.Filter
migrate_Pages_Routes_Filter__Filter old =
    { filter = old.filter |> migrate_Filter_Model
    , sorter = old.sorter |> migrate_Sorter_Model
    }


migrate_Pages_Routes_Filter__Metadata : Evergreen.V17.Pages.Routes.Filter_.Metadata -> Evergreen.V18.Pages.Routes.Filter_.Metadata
migrate_Pages_Routes_Filter__Metadata old =
    { expanded = old.expanded
    , routeId = old.routeId |> migrate_Route_RouteId
    , editRoute = old.editRoute |> Maybe.map migrate_RouteEditPane_Model
    }


migrate_Pages_Routes_Filter__Model : Evergreen.V17.Pages.Routes.Filter_.Model -> Evergreen.V18.Pages.Routes.Filter_.Model
migrate_Pages_Routes_Filter__Model old =
    { filter = old.filter |> migrate_Pages_Routes_Filter__Filter
    , showSortBox = old.showSortBox
    , metadatas = old.metadatas |> Dict.map (\k -> migrate_Pages_Routes_Filter__Metadata)
    }


migrate_Pages_SignIn_SignInDest__Model : Evergreen.V17.Pages.SignIn.SignInDest_.Model -> Evergreen.V18.Pages.SignIn.SignInDest_.Model
migrate_Pages_SignIn_SignInDest__Model old =
    old


migrate_Pages_Stats_Model : Evergreen.V17.Pages.Stats.Model -> Evergreen.V18.Pages.Stats.Model
migrate_Pages_Stats_Model old =
    old


migrate_RouteEditPane_Model : Evergreen.V17.RouteEditPane.Model -> Evergreen.V18.RouteEditPane.Model
migrate_RouteEditPane_Model old =
    { route = old.route |> migrate_Route_NewRouteData
    , datePickerModel = old.datePickerModel
    , datePickerText = old.datePickerText
    }


migrate_Route_ClimbType : Evergreen.V17.Route.ClimbType -> Evergreen.V18.Route.ClimbType
migrate_Route_ClimbType old =
    case old of
        Evergreen.V17.Route.Trad ->
            Evergreen.V18.Route.Trad

        Evergreen.V17.Route.Sport ->
            Evergreen.V18.Route.Sport

        Evergreen.V17.Route.Boulder ->
            Evergreen.V18.Route.Boulder

        Evergreen.V17.Route.Mix ->
            Evergreen.V18.Route.Mix

        Evergreen.V17.Route.Aid ->
            Evergreen.V18.Route.Aid


migrate_Route_NewRouteData : Evergreen.V17.Route.NewRouteData -> Evergreen.V18.Route.NewRouteData
migrate_Route_NewRouteData old =
    { name = old.name
    , area = old.area
    , grade = old.grade
    , notes = old.notes
    , tickDate2 = old.tickDate2
    , type_ = old.type_ |> migrate_Route_ClimbType
    , images = old.images
    , videos = old.videos
    }


migrate_Route_RouteData : Evergreen.V17.Route.RouteData -> Evergreen.V18.Route.RouteData
migrate_Route_RouteData old =
    { name = old.name
    , area = old.area
    , grade = old.grade
    , notes = old.notes
    , tickDate2 = old.tickDate2
    , type_ = old.type_ |> migrate_Route_ClimbType
    , images = old.images
    , videos = old.videos
    , id = old.id |> migrate_Route_RouteId
    }


migrate_Route_RouteId : Evergreen.V17.Route.RouteId -> Evergreen.V18.Route.RouteId
migrate_Route_RouteId old =
    case old of
        Evergreen.V17.Route.RouteId p0 ->
            Evergreen.V18.Route.RouteId p0


migrate_Shared_Model : Evergreen.V17.Shared.Model -> Evergreen.V18.Shared.Model
migrate_Shared_Model old =
    { routes = old.routes |> List.map migrate_Route_RouteData
    , user = old.user |> Maybe.map migrate_Shared_User
    , currentDate = old.currentDate
    }


migrate_Shared_User : Evergreen.V17.Shared.User -> Evergreen.V18.Shared.User
migrate_Shared_User old =
    case old of
        Evergreen.V17.Shared.NormalUser ->
            Evergreen.V18.Shared.NormalUser

        Evergreen.V17.Shared.AdminUser ->
            Evergreen.V18.Shared.AdminUser


migrate_Sorter_Model : Evergreen.V17.Sorter.Model -> Evergreen.V18.Sorter.Model
migrate_Sorter_Model old =
    old |> List.map (Tuple.mapBoth migrate_Sorter_SortAttribute migrate_Sorter_SortOrder)


migrate_Sorter_SortAttribute : Evergreen.V17.Sorter.SortAttribute -> Evergreen.V18.Sorter.SortAttribute
migrate_Sorter_SortAttribute old =
    case old of
        Evergreen.V17.Sorter.Area ->
            Evergreen.V18.Sorter.Area

        Evergreen.V17.Sorter.Grade ->
            Evergreen.V18.Sorter.Grade

        Evergreen.V17.Sorter.Tickdate ->
            Evergreen.V18.Sorter.Tickdate

        Evergreen.V17.Sorter.Name ->
            Evergreen.V18.Sorter.Name


migrate_Sorter_SortOrder : Evergreen.V17.Sorter.SortOrder -> Evergreen.V18.Sorter.SortOrder
migrate_Sorter_SortOrder old =
    case old of
        Evergreen.V17.Sorter.Ascending ->
            Evergreen.V18.Sorter.Ascending

        Evergreen.V17.Sorter.Descending ->
            Evergreen.V18.Sorter.Descending
