module Evergreen.Migrate.V23 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V22.BackupModel
import Evergreen.V22.Bridge
import Evergreen.V22.ConfirmComponent
import Evergreen.V22.Filter
import Evergreen.V22.FormDict
import Evergreen.V22.Gen.Model
import Evergreen.V22.Gen.Msg
import Evergreen.V22.Gen.Pages
import Evergreen.V22.Gen.Params.Routes.Filter_
import Evergreen.V22.Gen.Params.SignIn.SignInDest_
import Evergreen.V22.ImageGallery
import Evergreen.V22.Pages.Admin.AddUser
import Evergreen.V22.Pages.Admin.ChangePassword
import Evergreen.V22.Pages.Admin.Home_
import Evergreen.V22.Pages.Admin.RemoveUser
import Evergreen.V22.Pages.Admin.ShowJson
import Evergreen.V22.Pages.ChangePassword
import Evergreen.V22.Pages.Home_
import Evergreen.V22.Pages.InputJson
import Evergreen.V22.Pages.MoreOptions
import Evergreen.V22.Pages.NewRoute
import Evergreen.V22.Pages.OutputJson
import Evergreen.V22.Pages.Routes.Filter_
import Evergreen.V22.Pages.SignIn.SignInDest_
import Evergreen.V22.Pages.Stats
import Evergreen.V22.Route
import Evergreen.V22.RouteEditPane
import Evergreen.V22.Shared
import Evergreen.V22.Sorter
import Evergreen.V22.Types
import Evergreen.V23.BackupModel
import Evergreen.V23.Bridge
import Evergreen.V23.ConfirmComponent
import Evergreen.V23.Filter
import Evergreen.V23.FormDict
import Evergreen.V23.Gen.Model
import Evergreen.V23.Gen.Msg
import Evergreen.V23.Gen.Pages
import Evergreen.V23.Gen.Params.Routes.Filter_
import Evergreen.V23.Gen.Params.SignIn.SignInDest_
import Evergreen.V23.ImageGallery
import Evergreen.V23.Pages.Admin.AddUser
import Evergreen.V23.Pages.Admin.ChangePassword
import Evergreen.V23.Pages.Admin.Home_
import Evergreen.V23.Pages.Admin.RemoveUser
import Evergreen.V23.Pages.Admin.ShowJson
import Evergreen.V23.Pages.ChangePassword
import Evergreen.V23.Pages.Home_
import Evergreen.V23.Pages.InputJson
import Evergreen.V23.Pages.MoreOptions
import Evergreen.V23.Pages.NewRoute
import Evergreen.V23.Pages.OutputJson
import Evergreen.V23.Pages.Routes.Filter_
import Evergreen.V23.Pages.SignIn.SignInDest_
import Evergreen.V23.Pages.Stats
import Evergreen.V23.Route
import Evergreen.V23.RouteEditPane
import Evergreen.V23.Shared
import Evergreen.V23.Sorter
import Evergreen.V23.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Set


frontendModel : Evergreen.V22.Types.FrontendModel -> ModelMigration Evergreen.V23.Types.FrontendModel Evergreen.V23.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V22.Types.BackendModel -> ModelMigration Evergreen.V23.Types.BackendModel Evergreen.V23.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V22.Types.FrontendMsg -> MsgMigration Evergreen.V23.Types.FrontendMsg Evergreen.V23.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V22.Types.ToBackend -> MsgMigration Evergreen.V23.Types.ToBackend Evergreen.V23.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V22.Types.BackendMsg -> MsgMigration Evergreen.V23.Types.BackendMsg Evergreen.V23.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V22.Types.ToFrontend -> MsgMigration Evergreen.V23.Types.ToFrontend Evergreen.V23.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V22.Types.BackendModel -> Evergreen.V23.Types.BackendModel
migrate_Types_BackendModel old =
    { sessions = old.sessions
    , users = old.users |> Dict.map (\k -> migrate_Types_UserData)
    , currentTime = old.currentTime
    }


migrate_Types_FrontendModel : Evergreen.V22.Types.FrontendModel -> Evergreen.V23.Types.FrontendModel
migrate_Types_FrontendModel old =
    { url = old.url
    , key = old.key
    , shared = old.shared |> migrate_Shared_Model
    , page = old.page |> migrate_Gen_Pages_Model
    }


migrate_Types_ToBackend : Evergreen.V22.Types.ToBackend -> Evergreen.V23.Types.ToBackend
migrate_Types_ToBackend old =
    old |> migrate_Bridge_ToBackend


migrate_BackupModel_BackupModel : Evergreen.V22.BackupModel.BackupModel -> Evergreen.V23.BackupModel.BackupModel
migrate_BackupModel_BackupModel old =
    old
        |> List.map
            (\rec ->
                { username = rec.username
                , routes = rec.routes |> List.map migrate_Route_RouteData
                }
            )


migrate_Bridge_AdminMsg : Evergreen.V22.Bridge.AdminMsg -> Evergreen.V23.Bridge.AdminMsg
migrate_Bridge_AdminMsg old =
    case old of
        Evergreen.V22.Bridge.AddUser p0 ->
            Evergreen.V23.Bridge.AddUser p0

        Evergreen.V22.Bridge.RemoveUser p0 ->
            Evergreen.V23.Bridge.RemoveUser p0

        Evergreen.V22.Bridge.RequestModel ->
            Evergreen.V23.Bridge.RequestModel

        Evergreen.V22.Bridge.AdminMsgChangePassword p0 ->
            Evergreen.V23.Bridge.AdminMsgChangePassword p0


migrate_Bridge_ToBackend : Evergreen.V22.Bridge.ToBackend -> Evergreen.V23.Bridge.ToBackend
migrate_Bridge_ToBackend old =
    case old of
        Evergreen.V22.Bridge.UpdateRoute p0 ->
            Evergreen.V23.Bridge.UpdateRoute (p0 |> migrate_Route_RouteData)

        Evergreen.V22.Bridge.RemoveRoute p0 ->
            Evergreen.V23.Bridge.RemoveRoute (p0 |> migrate_Route_RouteId)

        Evergreen.V22.Bridge.ToBackendCreateNewRoute p0 ->
            Evergreen.V23.Bridge.ToBackendCreateNewRoute (p0 |> migrate_Route_NewRouteData)

        Evergreen.V22.Bridge.ToBackendLogOut ->
            Evergreen.V23.Bridge.ToBackendLogOut

        Evergreen.V22.Bridge.ToBackendResetRouteList p0 ->
            Evergreen.V23.Bridge.ToBackendResetRouteList (p0 |> List.map migrate_Route_NewRouteData)

        Evergreen.V22.Bridge.ToBackendLogIn p0 p1 ->
            Evergreen.V23.Bridge.ToBackendLogIn p0 p1

        Evergreen.V22.Bridge.ToBackendRefreshSession ->
            Evergreen.V23.Bridge.ToBackendRefreshSession

        Evergreen.V22.Bridge.ToBackendAdminMsg p0 ->
            Evergreen.V23.Bridge.ToBackendAdminMsg (p0 |> migrate_Bridge_AdminMsg)

        Evergreen.V22.Bridge.ToBackendUserChangePass p0 ->
            Evergreen.V23.Bridge.ToBackendUserChangePass p0

        Evergreen.V22.Bridge.NoOpToBackend ->
            Evergreen.V23.Bridge.NoOpToBackend


migrate_ConfirmComponent_Msg : Evergreen.V22.ConfirmComponent.Msg -> Evergreen.V23.ConfirmComponent.Msg
migrate_ConfirmComponent_Msg old =
    case old of
        Evergreen.V22.ConfirmComponent.ConfirmCompTextChange p0 ->
            Evergreen.V23.ConfirmComponent.ConfirmCompTextChange p0

        Evergreen.V22.ConfirmComponent.FirstButtonPressed ->
            Evergreen.V23.ConfirmComponent.FirstButtonPressed


migrate_ConfirmComponent_State : Evergreen.V22.ConfirmComponent.State -> Evergreen.V23.ConfirmComponent.State
migrate_ConfirmComponent_State old =
    case old of
        Evergreen.V22.ConfirmComponent.Waiting ->
            Evergreen.V23.ConfirmComponent.Waiting

        Evergreen.V22.ConfirmComponent.Active p0 ->
            Evergreen.V23.ConfirmComponent.Active p0


migrate_Filter_Model : Evergreen.V22.Filter.Model -> Evergreen.V23.Filter.Model
migrate_Filter_Model old =
    { grade = old.grade
    , type_ = old.type_
    , tickdate = old.tickdate |> migrate_Filter_TickDateFilter
    , tags = Set.empty
    }


migrate_Filter_Msg : Evergreen.V22.Filter.Msg -> Evergreen.V23.Filter.Msg
migrate_Filter_Msg old =
    case old of
        Evergreen.V22.Filter.PressedGradeFilter p0 ->
            Evergreen.V23.Filter.PressedGradeFilter p0

        Evergreen.V22.Filter.PressedTickdateFilter ->
            Evergreen.V23.Filter.PressedTickdateFilter

        Evergreen.V22.Filter.PressedTypeFilter p0 ->
            Evergreen.V23.Filter.PressedTypeFilter p0


migrate_Filter_TickDateFilter : Evergreen.V22.Filter.TickDateFilter -> Evergreen.V23.Filter.TickDateFilter
migrate_Filter_TickDateFilter old =
    case old of
        Evergreen.V22.Filter.TickdateRangeFrom ->
            Evergreen.V23.Filter.TickdateRangeFrom

        Evergreen.V22.Filter.TickdateRangeTo ->
            Evergreen.V23.Filter.TickdateRangeTo

        Evergreen.V22.Filter.TickdateRangeBetween ->
            Evergreen.V23.Filter.TickdateRangeBetween

        Evergreen.V22.Filter.ShowHasTickdate ->
            Evergreen.V23.Filter.ShowHasTickdate

        Evergreen.V22.Filter.ShowWithoutTickdate ->
            Evergreen.V23.Filter.ShowWithoutTickdate

        Evergreen.V22.Filter.ShowAllTickdates ->
            Evergreen.V23.Filter.ShowAllTickdates


migrate_FormDict_FormDict : Evergreen.V22.FormDict.FormDict -> Evergreen.V23.FormDict.FormDict
migrate_FormDict_FormDict old =
    case old of
        Evergreen.V22.FormDict.FormDict p0 ->
            Evergreen.V23.FormDict.FormDict p0


migrate_Gen_Model_Model : Evergreen.V22.Gen.Model.Model -> Evergreen.V23.Gen.Model.Model
migrate_Gen_Model_Model old =
    case old of
        Evergreen.V22.Gen.Model.Redirecting_ ->
            Evergreen.V23.Gen.Model.Redirecting_

        Evergreen.V22.Gen.Model.ChangePassword p0 p1 ->
            Evergreen.V23.Gen.Model.ChangePassword p0 (p1 |> migrate_Pages_ChangePassword_Model)

        Evergreen.V22.Gen.Model.Home_ p0 p1 ->
            Evergreen.V23.Gen.Model.Home_ p0 (p1 |> migrate_Pages_Home__Model)

        Evergreen.V22.Gen.Model.InputJson p0 p1 ->
            Evergreen.V23.Gen.Model.InputJson p0 (p1 |> migrate_Pages_InputJson_Model)

        Evergreen.V22.Gen.Model.MoreOptions p0 p1 ->
            Evergreen.V23.Gen.Model.MoreOptions p0 (p1 |> migrate_Pages_MoreOptions_Model)

        Evergreen.V22.Gen.Model.NewRoute p0 p1 ->
            Evergreen.V23.Gen.Model.NewRoute p0 (p1 |> migrate_Pages_NewRoute_Model)

        Evergreen.V22.Gen.Model.OutputJson p0 p1 ->
            Evergreen.V23.Gen.Model.OutputJson p0 (p1 |> migrate_Pages_OutputJson_Model)

        Evergreen.V22.Gen.Model.Stats p0 p1 ->
            Evergreen.V23.Gen.Model.Stats p0 (p1 |> migrate_Pages_Stats_Model)

        Evergreen.V22.Gen.Model.Admin__AddUser p0 p1 ->
            Evergreen.V23.Gen.Model.Admin__AddUser p0 (p1 |> migrate_Pages_Admin_AddUser_Model)

        Evergreen.V22.Gen.Model.Admin__ChangePassword p0 p1 ->
            Evergreen.V23.Gen.Model.Admin__ChangePassword p0
                (p1 |> migrate_Pages_Admin_ChangePassword_Model)

        Evergreen.V22.Gen.Model.Admin__Home_ p0 p1 ->
            Evergreen.V23.Gen.Model.Admin__Home_ p0 (p1 |> migrate_Pages_Admin_Home__Model)

        Evergreen.V22.Gen.Model.Admin__RemoveUser p0 p1 ->
            Evergreen.V23.Gen.Model.Admin__RemoveUser p0 (p1 |> migrate_Pages_Admin_RemoveUser_Model)

        Evergreen.V22.Gen.Model.Admin__ShowJson p0 p1 ->
            Evergreen.V23.Gen.Model.Admin__ShowJson p0 (p1 |> migrate_Pages_Admin_ShowJson_Model)

        Evergreen.V22.Gen.Model.Routes__Filter_ p0 p1 ->
            Evergreen.V23.Gen.Model.Routes__Filter_ (p0 |> migrate_Gen_Params_Routes_Filter__Params)
                (p1 |> migrate_Pages_Routes_Filter__Model)

        Evergreen.V22.Gen.Model.SignIn__SignInDest_ p0 p1 ->
            Evergreen.V23.Gen.Model.SignIn__SignInDest_ (p0 |> migrate_Gen_Params_SignIn_SignInDest__Params)
                (p1 |> migrate_Pages_SignIn_SignInDest__Model)

        Evergreen.V22.Gen.Model.NotFound p0 ->
            Evergreen.V23.Gen.Model.NotFound p0


migrate_Gen_Msg_Msg : Evergreen.V22.Gen.Msg.Msg -> Evergreen.V23.Gen.Msg.Msg
migrate_Gen_Msg_Msg old =
    case old of
        Evergreen.V22.Gen.Msg.ChangePassword p0 ->
            Evergreen.V23.Gen.Msg.ChangePassword (p0 |> migrate_Pages_ChangePassword_Msg)

        Evergreen.V22.Gen.Msg.Home_ p0 ->
            Evergreen.V23.Gen.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V22.Gen.Msg.InputJson p0 ->
            Evergreen.V23.Gen.Msg.InputJson (p0 |> migrate_Pages_InputJson_Msg)

        Evergreen.V22.Gen.Msg.MoreOptions p0 ->
            Evergreen.V23.Gen.Msg.MoreOptions (p0 |> migrate_Pages_MoreOptions_Msg)

        Evergreen.V22.Gen.Msg.NewRoute p0 ->
            Evergreen.V23.Gen.Msg.NewRoute (p0 |> migrate_Pages_NewRoute_Msg)

        Evergreen.V22.Gen.Msg.OutputJson p0 ->
            Evergreen.V23.Gen.Msg.OutputJson (p0 |> migrate_Pages_OutputJson_Msg)

        Evergreen.V22.Gen.Msg.Stats p0 ->
            Evergreen.V23.Gen.Msg.Stats (p0 |> migrate_Pages_Stats_Msg)

        Evergreen.V22.Gen.Msg.Admin__AddUser p0 ->
            Evergreen.V23.Gen.Msg.Admin__AddUser (p0 |> migrate_Pages_Admin_AddUser_Msg)

        Evergreen.V22.Gen.Msg.Admin__ChangePassword p0 ->
            Evergreen.V23.Gen.Msg.Admin__ChangePassword (p0 |> migrate_Pages_Admin_ChangePassword_Msg)

        Evergreen.V22.Gen.Msg.Admin__Home_ p0 ->
            Evergreen.V23.Gen.Msg.Admin__Home_ (p0 |> migrate_Pages_Admin_Home__Msg)

        Evergreen.V22.Gen.Msg.Admin__RemoveUser p0 ->
            Evergreen.V23.Gen.Msg.Admin__RemoveUser (p0 |> migrate_Pages_Admin_RemoveUser_Msg)

        Evergreen.V22.Gen.Msg.Admin__ShowJson p0 ->
            Evergreen.V23.Gen.Msg.Admin__ShowJson (p0 |> migrate_Pages_Admin_ShowJson_Msg)

        Evergreen.V22.Gen.Msg.Routes__Filter_ p0 ->
            Evergreen.V23.Gen.Msg.Routes__Filter_ (p0 |> migrate_Pages_Routes_Filter__Msg)

        Evergreen.V22.Gen.Msg.SignIn__SignInDest_ p0 ->
            Evergreen.V23.Gen.Msg.SignIn__SignInDest_ (p0 |> migrate_Pages_SignIn_SignInDest__Msg)


migrate_Gen_Pages_Model : Evergreen.V22.Gen.Pages.Model -> Evergreen.V23.Gen.Pages.Model
migrate_Gen_Pages_Model old =
    old |> migrate_Gen_Model_Model


migrate_Gen_Pages_Msg : Evergreen.V22.Gen.Pages.Msg -> Evergreen.V23.Gen.Pages.Msg
migrate_Gen_Pages_Msg old =
    old |> migrate_Gen_Msg_Msg


migrate_Gen_Params_Routes_Filter__Params : Evergreen.V22.Gen.Params.Routes.Filter_.Params -> Evergreen.V23.Gen.Params.Routes.Filter_.Params
migrate_Gen_Params_Routes_Filter__Params old =
    old


migrate_Gen_Params_SignIn_SignInDest__Params : Evergreen.V22.Gen.Params.SignIn.SignInDest_.Params -> Evergreen.V23.Gen.Params.SignIn.SignInDest_.Params
migrate_Gen_Params_SignIn_SignInDest__Params old =
    old


migrate_ImageGallery_Msg : Evergreen.V22.ImageGallery.Msg -> Evergreen.V23.ImageGallery.Msg
migrate_ImageGallery_Msg old =
    case old of
        Evergreen.V22.ImageGallery.PrevPressed ->
            Evergreen.V23.ImageGallery.PrevPressed

        Evergreen.V22.ImageGallery.NextPressed ->
            Evergreen.V23.ImageGallery.NextPressed

        Evergreen.V22.ImageGallery.BackPressed ->
            Evergreen.V23.ImageGallery.BackPressed


migrate_Pages_Admin_AddUser_Model : Evergreen.V22.Pages.Admin.AddUser.Model -> Evergreen.V23.Pages.Admin.AddUser.Model
migrate_Pages_Admin_AddUser_Model old =
    { form = old.form |> migrate_FormDict_FormDict
    }


migrate_Pages_Admin_AddUser_Msg : Evergreen.V22.Pages.Admin.AddUser.Msg -> Evergreen.V23.Pages.Admin.AddUser.Msg
migrate_Pages_Admin_AddUser_Msg old =
    case old of
        Evergreen.V22.Pages.Admin.AddUser.FieldUpdate p0 p1 ->
            Evergreen.V23.Pages.Admin.AddUser.FieldUpdate p0 p1

        Evergreen.V22.Pages.Admin.AddUser.CreateUser ->
            Evergreen.V23.Pages.Admin.AddUser.CreateUser


migrate_Pages_Admin_ChangePassword_Model : Evergreen.V22.Pages.Admin.ChangePassword.Model -> Evergreen.V23.Pages.Admin.ChangePassword.Model
migrate_Pages_Admin_ChangePassword_Model old =
    { form = old.form |> migrate_FormDict_FormDict
    }


migrate_Pages_Admin_ChangePassword_Msg : Evergreen.V22.Pages.Admin.ChangePassword.Msg -> Evergreen.V23.Pages.Admin.ChangePassword.Msg
migrate_Pages_Admin_ChangePassword_Msg old =
    case old of
        Evergreen.V22.Pages.Admin.ChangePassword.FieldUpdate p0 p1 ->
            Evergreen.V23.Pages.Admin.ChangePassword.FieldUpdate p0 p1

        Evergreen.V22.Pages.Admin.ChangePassword.ChangePassword ->
            Evergreen.V23.Pages.Admin.ChangePassword.ChangePassword


migrate_Pages_Admin_Home__Model : Evergreen.V22.Pages.Admin.Home_.Model -> Evergreen.V23.Pages.Admin.Home_.Model
migrate_Pages_Admin_Home__Model old =
    old


migrate_Pages_Admin_Home__Msg : Evergreen.V22.Pages.Admin.Home_.Msg -> Evergreen.V23.Pages.Admin.Home_.Msg
migrate_Pages_Admin_Home__Msg old =
    case old of
        Evergreen.V22.Pages.Admin.Home_.LogOut ->
            Evergreen.V23.Pages.Admin.Home_.LogOut


migrate_Pages_Admin_RemoveUser_Model : Evergreen.V22.Pages.Admin.RemoveUser.Model -> Evergreen.V23.Pages.Admin.RemoveUser.Model
migrate_Pages_Admin_RemoveUser_Model old =
    old


migrate_Pages_Admin_RemoveUser_Msg : Evergreen.V22.Pages.Admin.RemoveUser.Msg -> Evergreen.V23.Pages.Admin.RemoveUser.Msg
migrate_Pages_Admin_RemoveUser_Msg old =
    case old of
        Evergreen.V22.Pages.Admin.RemoveUser.FieldUpdate p0 ->
            Evergreen.V23.Pages.Admin.RemoveUser.FieldUpdate p0

        Evergreen.V22.Pages.Admin.RemoveUser.RemoveUser ->
            Evergreen.V23.Pages.Admin.RemoveUser.RemoveUser


migrate_Pages_Admin_ShowJson_Model : Evergreen.V22.Pages.Admin.ShowJson.Model -> Evergreen.V23.Pages.Admin.ShowJson.Model
migrate_Pages_Admin_ShowJson_Model old =
    old


migrate_Pages_Admin_ShowJson_Msg : Evergreen.V22.Pages.Admin.ShowJson.Msg -> Evergreen.V23.Pages.Admin.ShowJson.Msg
migrate_Pages_Admin_ShowJson_Msg old =
    case old of
        Evergreen.V22.Pages.Admin.ShowJson.BackupModelFromBackend p0 ->
            Evergreen.V23.Pages.Admin.ShowJson.BackupModelFromBackend (p0 |> migrate_BackupModel_BackupModel)


migrate_Pages_ChangePassword_Model : Evergreen.V22.Pages.ChangePassword.Model -> Evergreen.V23.Pages.ChangePassword.Model
migrate_Pages_ChangePassword_Model old =
    old


migrate_Pages_ChangePassword_Msg : Evergreen.V22.Pages.ChangePassword.Msg -> Evergreen.V23.Pages.ChangePassword.Msg
migrate_Pages_ChangePassword_Msg old =
    case old of
        Evergreen.V22.Pages.ChangePassword.FieldUpdate p0 p1 ->
            Evergreen.V23.Pages.ChangePassword.FieldUpdate p0 p1

        Evergreen.V22.Pages.ChangePassword.ChangePassword ->
            Evergreen.V23.Pages.ChangePassword.ChangePassword


migrate_Pages_Home__Model : Evergreen.V22.Pages.Home_.Model -> Evergreen.V23.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V22.Pages.Home_.Msg -> Evergreen.V23.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V22.Pages.Home_.ReplaceMe ->
            Evergreen.V23.Pages.Home_.ReplaceMe


migrate_Pages_InputJson_Model : Evergreen.V22.Pages.InputJson.Model -> Evergreen.V23.Pages.InputJson.Model
migrate_Pages_InputJson_Model old =
    { text = old.text
    , statusText = old.statusText
    , parsedRoutes = old.parsedRoutes |> Maybe.map (List.map migrate_Route_NewRouteData)
    , confirmState = old.confirmState |> migrate_ConfirmComponent_State
    }


migrate_Pages_InputJson_Msg : Evergreen.V22.Pages.InputJson.Msg -> Evergreen.V23.Pages.InputJson.Msg
migrate_Pages_InputJson_Msg old =
    case old of
        Evergreen.V22.Pages.InputJson.TextChanged p0 ->
            Evergreen.V23.Pages.InputJson.TextChanged p0

        Evergreen.V22.Pages.InputJson.SubmitToBackend p0 ->
            Evergreen.V23.Pages.InputJson.SubmitToBackend (p0 |> List.map migrate_Route_NewRouteData)

        Evergreen.V22.Pages.InputJson.ConfirmComponentEvent p0 ->
            Evergreen.V23.Pages.InputJson.ConfirmComponentEvent (p0 |> migrate_ConfirmComponent_Msg)


migrate_Pages_MoreOptions_Model : Evergreen.V22.Pages.MoreOptions.Model -> Evergreen.V23.Pages.MoreOptions.Model
migrate_Pages_MoreOptions_Model old =
    old


migrate_Pages_MoreOptions_Msg : Evergreen.V22.Pages.MoreOptions.Msg -> Evergreen.V23.Pages.MoreOptions.Msg
migrate_Pages_MoreOptions_Msg old =
    case old of
        Evergreen.V22.Pages.MoreOptions.Logout ->
            Evergreen.V23.Pages.MoreOptions.Logout


migrate_Pages_NewRoute_Model : Evergreen.V22.Pages.NewRoute.Model -> Evergreen.V23.Pages.NewRoute.Model
migrate_Pages_NewRoute_Model old =
    { newRouteData = old.newRouteData |> migrate_RouteEditPane_Model
    }


migrate_Pages_NewRoute_Msg : Evergreen.V22.Pages.NewRoute.Msg -> Evergreen.V23.Pages.NewRoute.Msg
migrate_Pages_NewRoute_Msg old =
    case old of
        Evergreen.V22.Pages.NewRoute.RouteEditMsg p0 ->
            Evergreen.V23.Pages.NewRoute.RouteEditMsg (p0 |> migrate_RouteEditPane_Msg)

        Evergreen.V22.Pages.NewRoute.CreateRoute ->
            Evergreen.V23.Pages.NewRoute.CreateRoute


migrate_Pages_OutputJson_Model : Evergreen.V22.Pages.OutputJson.Model -> Evergreen.V23.Pages.OutputJson.Model
migrate_Pages_OutputJson_Model old =
    old


migrate_Pages_OutputJson_Msg : Evergreen.V22.Pages.OutputJson.Msg -> Evergreen.V23.Pages.OutputJson.Msg
migrate_Pages_OutputJson_Msg old =
    case old of
        Evergreen.V22.Pages.OutputJson.NoOp ->
            Evergreen.V23.Pages.OutputJson.NoOp


migrate_Pages_Routes_Filter__ButtonId : Evergreen.V22.Pages.Routes.Filter_.ButtonId -> Evergreen.V23.Pages.Routes.Filter_.ButtonId
migrate_Pages_Routes_Filter__ButtonId old =
    case old of
        Evergreen.V22.Pages.Routes.Filter_.ExpandRouteButton p0 ->
            Evergreen.V23.Pages.Routes.Filter_.ExpandRouteButton (p0 |> migrate_Route_RouteId)

        Evergreen.V22.Pages.Routes.Filter_.EditRouteButton p0 ->
            Evergreen.V23.Pages.Routes.Filter_.EditRouteButton (p0 |> migrate_Route_RouteData)

        Evergreen.V22.Pages.Routes.Filter_.SaveButton p0 ->
            Evergreen.V23.Pages.Routes.Filter_.SaveButton (p0 |> migrate_Route_RouteData)

        Evergreen.V22.Pages.Routes.Filter_.DiscardButton p0 ->
            Evergreen.V23.Pages.Routes.Filter_.DiscardButton (p0 |> migrate_Route_RouteId)

        Evergreen.V22.Pages.Routes.Filter_.RemoveButton p0 ->
            Evergreen.V23.Pages.Routes.Filter_.RemoveButton (p0 |> migrate_Route_RouteId)

        Evergreen.V22.Pages.Routes.Filter_.CreateButton ->
            Evergreen.V23.Pages.Routes.Filter_.CreateButton


migrate_Pages_Routes_Filter__Filter : Evergreen.V22.Pages.Routes.Filter_.Filter -> Evergreen.V23.Pages.Routes.Filter_.Filter
migrate_Pages_Routes_Filter__Filter old =
    { filter = old.filter |> migrate_Filter_Model
    , sorter = old.sorter |> migrate_Sorter_Model
    }


migrate_Pages_Routes_Filter__Metadata : Evergreen.V22.Pages.Routes.Filter_.Metadata -> Evergreen.V23.Pages.Routes.Filter_.Metadata
migrate_Pages_Routes_Filter__Metadata old =
    { expanded = old.expanded
    , routeId = old.routeId |> migrate_Route_RouteId
    , editRoute = old.editRoute |> Maybe.map migrate_RouteEditPane_Model
    }


migrate_Pages_Routes_Filter__Model : Evergreen.V22.Pages.Routes.Filter_.Model -> Evergreen.V23.Pages.Routes.Filter_.Model
migrate_Pages_Routes_Filter__Model old =
    { filter = old.filter |> migrate_Pages_Routes_Filter__Filter
    , showSortBox = old.showSortBox
    , metadatas = old.metadatas |> Dict.map (\k -> migrate_Pages_Routes_Filter__Metadata)
    , galleryModel = old.galleryModel
    }


migrate_Pages_Routes_Filter__Msg : Evergreen.V22.Pages.Routes.Filter_.Msg -> Evergreen.V23.Pages.Routes.Filter_.Msg
migrate_Pages_Routes_Filter__Msg old =
    case old of
        Evergreen.V22.Pages.Routes.Filter_.ToggleFilters ->
            Evergreen.V23.Pages.Routes.Filter_.ToggleFilters

        Evergreen.V22.Pages.Routes.Filter_.ButtonPressed p0 ->
            Evergreen.V23.Pages.Routes.Filter_.ButtonPressed (p0 |> migrate_Pages_Routes_Filter__ButtonId)

        Evergreen.V22.Pages.Routes.Filter_.SortSelected p0 ->
            Evergreen.V23.Pages.Routes.Filter_.SortSelected (p0 |> migrate_Sorter_SorterMsg)

        Evergreen.V22.Pages.Routes.Filter_.FilterMsg p0 ->
            Evergreen.V23.Pages.Routes.Filter_.FilterMsg (p0 |> migrate_Filter_Msg)

        Evergreen.V22.Pages.Routes.Filter_.RouteEditPaneMsg p0 p1 ->
            Evergreen.V23.Pages.Routes.Filter_.RouteEditPaneMsg (p0 |> migrate_Route_RouteId)
                (p1 |> migrate_RouteEditPane_Msg)

        Evergreen.V22.Pages.Routes.Filter_.GalleryMsg p0 ->
            Evergreen.V23.Pages.Routes.Filter_.GalleryMsg (p0 |> migrate_ImageGallery_Msg)

        Evergreen.V22.Pages.Routes.Filter_.ThumbnailPressed p0 p1 ->
            Evergreen.V23.Pages.Routes.Filter_.ThumbnailPressed p0 p1


migrate_Pages_SignIn_SignInDest__FieldType : Evergreen.V22.Pages.SignIn.SignInDest_.FieldType -> Evergreen.V23.Pages.SignIn.SignInDest_.FieldType
migrate_Pages_SignIn_SignInDest__FieldType old =
    case old of
        Evergreen.V22.Pages.SignIn.SignInDest_.UsernameField ->
            Evergreen.V23.Pages.SignIn.SignInDest_.UsernameField

        Evergreen.V22.Pages.SignIn.SignInDest_.PasswordField ->
            Evergreen.V23.Pages.SignIn.SignInDest_.PasswordField


migrate_Pages_SignIn_SignInDest__Model : Evergreen.V22.Pages.SignIn.SignInDest_.Model -> Evergreen.V23.Pages.SignIn.SignInDest_.Model
migrate_Pages_SignIn_SignInDest__Model old =
    old


migrate_Pages_SignIn_SignInDest__Msg : Evergreen.V22.Pages.SignIn.SignInDest_.Msg -> Evergreen.V23.Pages.SignIn.SignInDest_.Msg
migrate_Pages_SignIn_SignInDest__Msg old =
    case old of
        Evergreen.V22.Pages.SignIn.SignInDest_.ClickedSignIn ->
            Evergreen.V23.Pages.SignIn.SignInDest_.ClickedSignIn

        Evergreen.V22.Pages.SignIn.SignInDest_.FieldChanged p0 p1 ->
            Evergreen.V23.Pages.SignIn.SignInDest_.FieldChanged (p0 |> migrate_Pages_SignIn_SignInDest__FieldType)
                p1

        Evergreen.V22.Pages.SignIn.SignInDest_.ToggleShowPassword ->
            Evergreen.V23.Pages.SignIn.SignInDest_.ToggleShowPassword

        Evergreen.V22.Pages.SignIn.SignInDest_.WrongUsernameOrPassword ->
            Evergreen.V23.Pages.SignIn.SignInDest_.WrongUsernameOrPassword


migrate_Pages_Stats_Model : Evergreen.V22.Pages.Stats.Model -> Evergreen.V23.Pages.Stats.Model
migrate_Pages_Stats_Model old =
    old


migrate_Pages_Stats_Msg : Evergreen.V22.Pages.Stats.Msg -> Evergreen.V23.Pages.Stats.Msg
migrate_Pages_Stats_Msg old =
    case old of
        Evergreen.V22.Pages.Stats.ReplaceMe ->
            Evergreen.V23.Pages.Stats.ReplaceMe


migrate_RouteEditPane_Model : Evergreen.V22.RouteEditPane.Model -> Evergreen.V23.RouteEditPane.Model
migrate_RouteEditPane_Model old =
    { route = old.route |> migrate_Route_NewRouteData
    , datePickerModel = old.datePickerModel
    , datePickerText = old.datePickerText
    , picturesText = old.picturesText
    , tagText = ""
    }


migrate_RouteEditPane_Msg : Evergreen.V22.RouteEditPane.Msg -> Evergreen.V23.RouteEditPane.Msg
migrate_RouteEditPane_Msg old =
    case old of
        Evergreen.V22.RouteEditPane.FieldUpdated p0 p1 ->
            Evergreen.V23.RouteEditPane.FieldUpdated p0 p1

        Evergreen.V22.RouteEditPane.DatePickerUpdate p0 ->
            Evergreen.V23.RouteEditPane.DatePickerUpdate p0


migrate_Route_ClimbType : Evergreen.V22.Route.ClimbType -> Evergreen.V23.Route.ClimbType
migrate_Route_ClimbType old =
    case old of
        Evergreen.V22.Route.Trad ->
            Evergreen.V23.Route.Trad

        Evergreen.V22.Route.Sport ->
            Evergreen.V23.Route.Sport

        Evergreen.V22.Route.Boulder ->
            Evergreen.V23.Route.Boulder

        Evergreen.V22.Route.Mix ->
            Evergreen.V23.Route.Mix

        Evergreen.V22.Route.Aid ->
            Evergreen.V23.Route.Aid


migrate_Route_NewRouteData : Evergreen.V22.Route.NewRouteData -> Evergreen.V23.Route.NewRouteData
migrate_Route_NewRouteData old =
    { name = old.name
    , area = old.area
    , grade = old.grade
    , notes = old.notes
    , tags = []
    , tickDate2 = old.tickDate2
    , type_ = old.type_ |> migrate_Route_ClimbType
    , images = old.images
    , videos = old.videos
    }


migrate_Route_RouteData : Evergreen.V22.Route.RouteData -> Evergreen.V23.Route.RouteData
migrate_Route_RouteData old =
    { name = old.name
    , area = old.area
    , grade = old.grade
    , notes = old.notes
    , tags = []
    , tickDate2 = old.tickDate2
    , type_ = old.type_ |> migrate_Route_ClimbType
    , images = old.images
    , videos = old.videos
    , id = old.id |> migrate_Route_RouteId
    }


migrate_Route_RouteId : Evergreen.V22.Route.RouteId -> Evergreen.V23.Route.RouteId
migrate_Route_RouteId old =
    case old of
        Evergreen.V22.Route.RouteId p0 ->
            Evergreen.V23.Route.RouteId p0


migrate_Shared_Model : Evergreen.V22.Shared.Model -> Evergreen.V23.Shared.Model
migrate_Shared_Model old =
    { routes = old.routes |> List.map migrate_Route_RouteData
    , user = old.user |> Maybe.map migrate_Shared_User
    , currentDate = old.currentDate
    }


migrate_Shared_Msg : Evergreen.V22.Shared.Msg -> Evergreen.V23.Shared.Msg
migrate_Shared_Msg old =
    case old of
        Evergreen.V22.Shared.Noop ->
            Evergreen.V23.Shared.Noop

        Evergreen.V22.Shared.MsgFromBackend p0 ->
            Evergreen.V23.Shared.MsgFromBackend (p0 |> migrate_Shared_SharedFromBackend)

        Evergreen.V22.Shared.SetCurrentDate p0 ->
            Evergreen.V23.Shared.SetCurrentDate p0


migrate_Shared_SharedFromBackend : Evergreen.V22.Shared.SharedFromBackend -> Evergreen.V23.Shared.SharedFromBackend
migrate_Shared_SharedFromBackend old =
    case old of
        Evergreen.V22.Shared.AllRoutesAnnouncement p0 ->
            Evergreen.V23.Shared.AllRoutesAnnouncement (p0 |> List.map migrate_Route_RouteData)

        Evergreen.V22.Shared.LogOut ->
            Evergreen.V23.Shared.LogOut

        Evergreen.V22.Shared.YouAreAdmin ->
            Evergreen.V23.Shared.YouAreAdmin


migrate_Shared_User : Evergreen.V22.Shared.User -> Evergreen.V23.Shared.User
migrate_Shared_User old =
    case old of
        Evergreen.V22.Shared.NormalUser ->
            Evergreen.V23.Shared.NormalUser

        Evergreen.V22.Shared.AdminUser ->
            Evergreen.V23.Shared.AdminUser


migrate_Sorter_Model : Evergreen.V22.Sorter.Model -> Evergreen.V23.Sorter.Model
migrate_Sorter_Model old =
    old |> List.map (Tuple.mapBoth migrate_Sorter_SortAttribute migrate_Sorter_SortOrder)


migrate_Sorter_SortAttribute : Evergreen.V22.Sorter.SortAttribute -> Evergreen.V23.Sorter.SortAttribute
migrate_Sorter_SortAttribute old =
    case old of
        Evergreen.V22.Sorter.Area ->
            Evergreen.V23.Sorter.Area

        Evergreen.V22.Sorter.Grade ->
            Evergreen.V23.Sorter.Grade

        Evergreen.V22.Sorter.Tickdate ->
            Evergreen.V23.Sorter.Tickdate

        Evergreen.V22.Sorter.Name ->
            Evergreen.V23.Sorter.Name


migrate_Sorter_SortOrder : Evergreen.V22.Sorter.SortOrder -> Evergreen.V23.Sorter.SortOrder
migrate_Sorter_SortOrder old =
    case old of
        Evergreen.V22.Sorter.Ascending ->
            Evergreen.V23.Sorter.Ascending

        Evergreen.V22.Sorter.Descending ->
            Evergreen.V23.Sorter.Descending


migrate_Sorter_SorterMsg : Evergreen.V22.Sorter.SorterMsg -> Evergreen.V23.Sorter.SorterMsg
migrate_Sorter_SorterMsg old =
    case old of
        Evergreen.V22.Sorter.SorterMsg p0 ->
            Evergreen.V23.Sorter.SorterMsg p0

        Evergreen.V22.Sorter.RemoveRow p0 ->
            Evergreen.V23.Sorter.RemoveRow p0


migrate_Types_FrontendMsg : Evergreen.V22.Types.FrontendMsg -> Evergreen.V23.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V22.Types.ClickedLink p0 ->
            Evergreen.V23.Types.ClickedLink p0

        Evergreen.V22.Types.ChangedUrl p0 ->
            Evergreen.V23.Types.ChangedUrl p0

        Evergreen.V22.Types.Shared p0 ->
            Evergreen.V23.Types.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V22.Types.Page p0 ->
            Evergreen.V23.Types.Page (p0 |> migrate_Gen_Pages_Msg)

        Evergreen.V22.Types.NoOpFrontendMsg ->
            Evergreen.V23.Types.NoOpFrontendMsg


migrate_Types_ToFrontend : Evergreen.V22.Types.ToFrontend -> Evergreen.V23.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V22.Types.AllRoutesAnnouncement p0 ->
            Evergreen.V23.Types.AllRoutesAnnouncement (p0 |> List.map migrate_Route_RouteData)

        Evergreen.V22.Types.ToFrontendUserNewPasswordAccepted ->
            Evergreen.V23.Types.ToFrontendUserNewPasswordAccepted

        Evergreen.V22.Types.ToFrontendUserNewPasswordRejected ->
            Evergreen.V23.Types.ToFrontendUserNewPasswordRejected

        Evergreen.V22.Types.ToFrontendYouAreAdmin ->
            Evergreen.V23.Types.ToFrontendYouAreAdmin

        Evergreen.V22.Types.ToFrontendAdminWholeModel p0 ->
            Evergreen.V23.Types.ToFrontendAdminWholeModel (p0 |> migrate_BackupModel_BackupModel)

        Evergreen.V22.Types.ToFrontendWrongUserNamePassword ->
            Evergreen.V23.Types.ToFrontendWrongUserNamePassword

        Evergreen.V22.Types.ToFrontendYourNotLoggedIn ->
            Evergreen.V23.Types.ToFrontendYourNotLoggedIn

        Evergreen.V22.Types.NoOpToFrontend ->
            Evergreen.V23.Types.NoOpToFrontend


migrate_Types_UserData : Evergreen.V22.Types.UserData -> Evergreen.V23.Types.UserData
migrate_Types_UserData old =
    { username = old.username
    , password = old.password
    , routes = old.routes |> List.map migrate_Route_RouteData
    , nextId = old.nextId |> migrate_Route_RouteId
    }
